/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InspectionsRouteImport } from './routes/inspections'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminInspectionsRouteImport } from './routes/admin/inspections'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPropertiesRouteImport } from './routes/admin/properties'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSuspensionsRouteImport } from './routes/admin/suspensions'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVerificationRouteImport } from './routes/admin/verification'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as AgentAvailabilityRouteImport } from './routes/agent/availability'
import { Route as AgentInspectionsRouteImport } from './routes/agent/inspections'
import { Route as AgentLeadsRouteImport } from './routes/agent/leads'
import { Route as AgentMessagesRouteImport } from './routes/agent/messages'
import { Route as AgentPaymentsRouteImport } from './routes/agent/payments'
import { Route as AgentProfileRouteImport } from './routes/agent/profile'
import { Route as AgentVerificationRouteImport } from './routes/agent/verification'
import { Route as InspectorAvailabilityRouteImport } from './routes/inspector/availability'
import { Route as InspectorDashboardRouteImport } from './routes/inspector/dashboard'
import { Route as InspectorEarningsRouteImport } from './routes/inspector/earnings'
import { Route as InspectorProfileRouteImport } from './routes/inspector/profile'
import { Route as InspectorReportsRouteImport } from './routes/inspector/reports'
import { Route as LandlordIndexRouteImport } from './routes/landlord/index'
import { Route as LandlordAgentsRouteImport } from './routes/landlord/agents'
import { Route as LandlordInspectionsRouteImport } from './routes/landlord/inspections'
import { Route as LandlordMessagesRouteImport } from './routes/landlord/messages'
import { Route as LandlordPaymentsRouteImport } from './routes/landlord/payments'
import { Route as LandlordProfileRouteImport } from './routes/landlord/profile'
import { Route as LandlordVerificationRouteImport } from './routes/landlord/verification'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as PropertiesIdRouteImport } from './routes/properties/$id'
import { Route as RoommatesIndexRouteImport } from './routes/roommates/index'
import { Route as RoommatesIdRouteImport } from './routes/roommates/$id'
import { Route as RoommatesNewRouteImport } from './routes/roommates/new'
import { Route as AdminAgreementsIndexRouteImport } from './routes/admin/agreements/index'
import { Route as AdminAgreementsIdRouteImport } from './routes/admin/agreements/$id'
import { Route as AgentAgreementsIndexRouteImport } from './routes/agent/agreements/index'
import { Route as AgentAgreementsIdRouteImport } from './routes/agent/agreements/$id'
import { Route as AgentPropertiesIndexRouteImport } from './routes/agent/properties/index'
import { Route as AgentPropertiesNewRouteImport } from './routes/agent/properties/new'
import { Route as InspectorInspectionsIndexRouteImport } from './routes/inspector/inspections/index'
import { Route as InspectorInspectionsIdRouteImport } from './routes/inspector/inspections/$id'
import { Route as LandlordAgreementsIndexRouteImport } from './routes/landlord/agreements/index'
import { Route as LandlordAgreementsIdRouteImport } from './routes/landlord/agreements/$id'
import { Route as LandlordPropertiesIndexRouteImport } from './routes/landlord/properties/index'
import { Route as LandlordPropertiesNewRouteImport } from './routes/landlord/properties/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsRoute = InspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInspectionsRoute = AdminInspectionsRouteImport.update({
  id: '/admin/inspections',
  path: '/admin/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/admin/properties',
  path: '/admin/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuspensionsRoute = AdminSuspensionsRouteImport.update({
  id: '/admin/suspensions',
  path: '/admin/suspensions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAvailabilityRoute = AgentAvailabilityRouteImport.update({
  id: '/agent/availability',
  path: '/agent/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentInspectionsRoute = AgentInspectionsRouteImport.update({
  id: '/agent/inspections',
  path: '/agent/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLeadsRoute = AgentLeadsRouteImport.update({
  id: '/agent/leads',
  path: '/agent/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMessagesRoute = AgentMessagesRouteImport.update({
  id: '/agent/messages',
  path: '/agent/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPaymentsRoute = AgentPaymentsRouteImport.update({
  id: '/agent/payments',
  path: '/agent/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentProfileRoute = AgentProfileRouteImport.update({
  id: '/agent/profile',
  path: '/agent/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentVerificationRoute = AgentVerificationRouteImport.update({
  id: '/agent/verification',
  path: '/agent/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorAvailabilityRoute = InspectorAvailabilityRouteImport.update({
  id: '/inspector/availability',
  path: '/inspector/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorDashboardRoute = InspectorDashboardRouteImport.update({
  id: '/inspector/dashboard',
  path: '/inspector/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorEarningsRoute = InspectorEarningsRouteImport.update({
  id: '/inspector/earnings',
  path: '/inspector/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorProfileRoute = InspectorProfileRouteImport.update({
  id: '/inspector/profile',
  path: '/inspector/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorReportsRoute = InspectorReportsRouteImport.update({
  id: '/inspector/reports',
  path: '/inspector/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordIndexRoute = LandlordIndexRouteImport.update({
  id: '/landlord/',
  path: '/landlord/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordAgentsRoute = LandlordAgentsRouteImport.update({
  id: '/landlord/agents',
  path: '/landlord/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordInspectionsRoute = LandlordInspectionsRouteImport.update({
  id: '/landlord/inspections',
  path: '/landlord/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordMessagesRoute = LandlordMessagesRouteImport.update({
  id: '/landlord/messages',
  path: '/landlord/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordPaymentsRoute = LandlordPaymentsRouteImport.update({
  id: '/landlord/payments',
  path: '/landlord/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordProfileRoute = LandlordProfileRouteImport.update({
  id: '/landlord/profile',
  path: '/landlord/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordVerificationRoute = LandlordVerificationRouteImport.update({
  id: '/landlord/verification',
  path: '/landlord/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoommatesIndexRoute = RoommatesIndexRouteImport.update({
  id: '/roommates/',
  path: '/roommates/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoommatesIdRoute = RoommatesIdRouteImport.update({
  id: '/roommates/$id',
  path: '/roommates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoommatesNewRoute = RoommatesNewRouteImport.update({
  id: '/roommates/new',
  path: '/roommates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgreementsIndexRoute = AdminAgreementsIndexRouteImport.update({
  id: '/admin/agreements/',
  path: '/admin/agreements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgreementsIdRoute = AdminAgreementsIdRouteImport.update({
  id: '/admin/agreements/$id',
  path: '/admin/agreements/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAgreementsIndexRoute = AgentAgreementsIndexRouteImport.update({
  id: '/agent/agreements/',
  path: '/agent/agreements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAgreementsIdRoute = AgentAgreementsIdRouteImport.update({
  id: '/agent/agreements/$id',
  path: '/agent/agreements/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPropertiesIndexRoute = AgentPropertiesIndexRouteImport.update({
  id: '/agent/properties/',
  path: '/agent/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPropertiesNewRoute = AgentPropertiesNewRouteImport.update({
  id: '/agent/properties/new',
  path: '/agent/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorInspectionsIndexRoute =
  InspectorInspectionsIndexRouteImport.update({
    id: '/inspector/inspections/',
    path: '/inspector/inspections/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InspectorInspectionsIdRoute = InspectorInspectionsIdRouteImport.update({
  id: '/inspector/inspections/$id',
  path: '/inspector/inspections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordAgreementsIndexRoute = LandlordAgreementsIndexRouteImport.update({
  id: '/landlord/agreements/',
  path: '/landlord/agreements/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordAgreementsIdRoute = LandlordAgreementsIdRouteImport.update({
  id: '/landlord/agreements/$id',
  path: '/landlord/agreements/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordPropertiesIndexRoute = LandlordPropertiesIndexRouteImport.update({
  id: '/landlord/properties/',
  path: '/landlord/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordPropertiesNewRoute = LandlordPropertiesNewRouteImport.update({
  id: '/landlord/properties/new',
  path: '/landlord/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/inspections': typeof InspectionsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suspensions': typeof AdminSuspensionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/agent/availability': typeof AgentAvailabilityRoute
  '/agent/inspections': typeof AgentInspectionsRoute
  '/agent/leads': typeof AgentLeadsRoute
  '/agent/messages': typeof AgentMessagesRoute
  '/agent/payments': typeof AgentPaymentsRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/verification': typeof AgentVerificationRoute
  '/inspector/availability': typeof InspectorAvailabilityRoute
  '/inspector/dashboard': typeof InspectorDashboardRoute
  '/inspector/earnings': typeof InspectorEarningsRoute
  '/inspector/profile': typeof InspectorProfileRoute
  '/inspector/reports': typeof InspectorReportsRoute
  '/landlord/agents': typeof LandlordAgentsRoute
  '/landlord/inspections': typeof LandlordInspectionsRoute
  '/landlord/messages': typeof LandlordMessagesRoute
  '/landlord/payments': typeof LandlordPaymentsRoute
  '/landlord/profile': typeof LandlordProfileRoute
  '/landlord/verification': typeof LandlordVerificationRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/roommates/$id': typeof RoommatesIdRoute
  '/roommates/new': typeof RoommatesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/landlord/': typeof LandlordIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/roommates/': typeof RoommatesIndexRoute
  '/admin/agreements/$id': typeof AdminAgreementsIdRoute
  '/agent/agreements/$id': typeof AgentAgreementsIdRoute
  '/agent/properties/new': typeof AgentPropertiesNewRoute
  '/inspector/inspections/$id': typeof InspectorInspectionsIdRoute
  '/landlord/agreements/$id': typeof LandlordAgreementsIdRoute
  '/landlord/properties/new': typeof LandlordPropertiesNewRoute
  '/admin/agreements/': typeof AdminAgreementsIndexRoute
  '/agent/agreements/': typeof AgentAgreementsIndexRoute
  '/agent/properties/': typeof AgentPropertiesIndexRoute
  '/inspector/inspections/': typeof InspectorInspectionsIndexRoute
  '/landlord/agreements/': typeof LandlordAgreementsIndexRoute
  '/landlord/properties/': typeof LandlordPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/inspections': typeof InspectionsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suspensions': typeof AdminSuspensionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/agent/availability': typeof AgentAvailabilityRoute
  '/agent/inspections': typeof AgentInspectionsRoute
  '/agent/leads': typeof AgentLeadsRoute
  '/agent/messages': typeof AgentMessagesRoute
  '/agent/payments': typeof AgentPaymentsRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/verification': typeof AgentVerificationRoute
  '/inspector/availability': typeof InspectorAvailabilityRoute
  '/inspector/dashboard': typeof InspectorDashboardRoute
  '/inspector/earnings': typeof InspectorEarningsRoute
  '/inspector/profile': typeof InspectorProfileRoute
  '/inspector/reports': typeof InspectorReportsRoute
  '/landlord/agents': typeof LandlordAgentsRoute
  '/landlord/inspections': typeof LandlordInspectionsRoute
  '/landlord/messages': typeof LandlordMessagesRoute
  '/landlord/payments': typeof LandlordPaymentsRoute
  '/landlord/profile': typeof LandlordProfileRoute
  '/landlord/verification': typeof LandlordVerificationRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/roommates/$id': typeof RoommatesIdRoute
  '/roommates/new': typeof RoommatesNewRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/landlord': typeof LandlordIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/roommates': typeof RoommatesIndexRoute
  '/admin/agreements/$id': typeof AdminAgreementsIdRoute
  '/agent/agreements/$id': typeof AgentAgreementsIdRoute
  '/agent/properties/new': typeof AgentPropertiesNewRoute
  '/inspector/inspections/$id': typeof InspectorInspectionsIdRoute
  '/landlord/agreements/$id': typeof LandlordAgreementsIdRoute
  '/landlord/properties/new': typeof LandlordPropertiesNewRoute
  '/admin/agreements': typeof AdminAgreementsIndexRoute
  '/agent/agreements': typeof AgentAgreementsIndexRoute
  '/agent/properties': typeof AgentPropertiesIndexRoute
  '/inspector/inspections': typeof InspectorInspectionsIndexRoute
  '/landlord/agreements': typeof LandlordAgreementsIndexRoute
  '/landlord/properties': typeof LandlordPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/inspections': typeof InspectionsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suspensions': typeof AdminSuspensionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/agent/availability': typeof AgentAvailabilityRoute
  '/agent/inspections': typeof AgentInspectionsRoute
  '/agent/leads': typeof AgentLeadsRoute
  '/agent/messages': typeof AgentMessagesRoute
  '/agent/payments': typeof AgentPaymentsRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/verification': typeof AgentVerificationRoute
  '/inspector/availability': typeof InspectorAvailabilityRoute
  '/inspector/dashboard': typeof InspectorDashboardRoute
  '/inspector/earnings': typeof InspectorEarningsRoute
  '/inspector/profile': typeof InspectorProfileRoute
  '/inspector/reports': typeof InspectorReportsRoute
  '/landlord/agents': typeof LandlordAgentsRoute
  '/landlord/inspections': typeof LandlordInspectionsRoute
  '/landlord/messages': typeof LandlordMessagesRoute
  '/landlord/payments': typeof LandlordPaymentsRoute
  '/landlord/profile': typeof LandlordProfileRoute
  '/landlord/verification': typeof LandlordVerificationRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/roommates/$id': typeof RoommatesIdRoute
  '/roommates/new': typeof RoommatesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/landlord/': typeof LandlordIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/roommates/': typeof RoommatesIndexRoute
  '/admin/agreements/$id': typeof AdminAgreementsIdRoute
  '/agent/agreements/$id': typeof AgentAgreementsIdRoute
  '/agent/properties/new': typeof AgentPropertiesNewRoute
  '/inspector/inspections/$id': typeof InspectorInspectionsIdRoute
  '/landlord/agreements/$id': typeof LandlordAgreementsIdRoute
  '/landlord/properties/new': typeof LandlordPropertiesNewRoute
  '/admin/agreements/': typeof AdminAgreementsIndexRoute
  '/agent/agreements/': typeof AgentAgreementsIndexRoute
  '/agent/properties/': typeof AgentPropertiesIndexRoute
  '/inspector/inspections/': typeof InspectorInspectionsIndexRoute
  '/landlord/agreements/': typeof LandlordAgreementsIndexRoute
  '/landlord/properties/': typeof LandlordPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/forgot-password'
    | '/how-it-works'
    | '/inspections'
    | '/login'
    | '/messages'
    | '/payments'
    | '/profile'
    | '/register'
    | '/saved'
    | '/admin/audit-logs'
    | '/admin/inspections'
    | '/admin/payments'
    | '/admin/properties'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/suspensions'
    | '/admin/users'
    | '/admin/verification'
    | '/agent/availability'
    | '/agent/inspections'
    | '/agent/leads'
    | '/agent/messages'
    | '/agent/payments'
    | '/agent/profile'
    | '/agent/verification'
    | '/inspector/availability'
    | '/inspector/dashboard'
    | '/inspector/earnings'
    | '/inspector/profile'
    | '/inspector/reports'
    | '/landlord/agents'
    | '/landlord/inspections'
    | '/landlord/messages'
    | '/landlord/payments'
    | '/landlord/profile'
    | '/landlord/verification'
    | '/properties/$id'
    | '/roommates/$id'
    | '/roommates/new'
    | '/admin/'
    | '/agent/'
    | '/landlord/'
    | '/properties/'
    | '/roommates/'
    | '/admin/agreements/$id'
    | '/agent/agreements/$id'
    | '/agent/properties/new'
    | '/inspector/inspections/$id'
    | '/landlord/agreements/$id'
    | '/landlord/properties/new'
    | '/admin/agreements/'
    | '/agent/agreements/'
    | '/agent/properties/'
    | '/inspector/inspections/'
    | '/landlord/agreements/'
    | '/landlord/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/forgot-password'
    | '/how-it-works'
    | '/inspections'
    | '/login'
    | '/messages'
    | '/payments'
    | '/profile'
    | '/register'
    | '/saved'
    | '/admin/audit-logs'
    | '/admin/inspections'
    | '/admin/payments'
    | '/admin/properties'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/suspensions'
    | '/admin/users'
    | '/admin/verification'
    | '/agent/availability'
    | '/agent/inspections'
    | '/agent/leads'
    | '/agent/messages'
    | '/agent/payments'
    | '/agent/profile'
    | '/agent/verification'
    | '/inspector/availability'
    | '/inspector/dashboard'
    | '/inspector/earnings'
    | '/inspector/profile'
    | '/inspector/reports'
    | '/landlord/agents'
    | '/landlord/inspections'
    | '/landlord/messages'
    | '/landlord/payments'
    | '/landlord/profile'
    | '/landlord/verification'
    | '/properties/$id'
    | '/roommates/$id'
    | '/roommates/new'
    | '/admin'
    | '/agent'
    | '/landlord'
    | '/properties'
    | '/roommates'
    | '/admin/agreements/$id'
    | '/agent/agreements/$id'
    | '/agent/properties/new'
    | '/inspector/inspections/$id'
    | '/landlord/agreements/$id'
    | '/landlord/properties/new'
    | '/admin/agreements'
    | '/agent/agreements'
    | '/agent/properties'
    | '/inspector/inspections'
    | '/landlord/agreements'
    | '/landlord/properties'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/forgot-password'
    | '/how-it-works'
    | '/inspections'
    | '/login'
    | '/messages'
    | '/payments'
    | '/profile'
    | '/register'
    | '/saved'
    | '/admin/audit-logs'
    | '/admin/inspections'
    | '/admin/payments'
    | '/admin/properties'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/suspensions'
    | '/admin/users'
    | '/admin/verification'
    | '/agent/availability'
    | '/agent/inspections'
    | '/agent/leads'
    | '/agent/messages'
    | '/agent/payments'
    | '/agent/profile'
    | '/agent/verification'
    | '/inspector/availability'
    | '/inspector/dashboard'
    | '/inspector/earnings'
    | '/inspector/profile'
    | '/inspector/reports'
    | '/landlord/agents'
    | '/landlord/inspections'
    | '/landlord/messages'
    | '/landlord/payments'
    | '/landlord/profile'
    | '/landlord/verification'
    | '/properties/$id'
    | '/roommates/$id'
    | '/roommates/new'
    | '/admin/'
    | '/agent/'
    | '/landlord/'
    | '/properties/'
    | '/roommates/'
    | '/admin/agreements/$id'
    | '/agent/agreements/$id'
    | '/agent/properties/new'
    | '/inspector/inspections/$id'
    | '/landlord/agreements/$id'
    | '/landlord/properties/new'
    | '/admin/agreements/'
    | '/agent/agreements/'
    | '/agent/properties/'
    | '/inspector/inspections/'
    | '/landlord/agreements/'
    | '/landlord/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InspectionsRoute: typeof InspectionsRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SavedRoute: typeof SavedRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminInspectionsRoute: typeof AdminInspectionsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSuspensionsRoute: typeof AdminSuspensionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AgentAvailabilityRoute: typeof AgentAvailabilityRoute
  AgentInspectionsRoute: typeof AgentInspectionsRoute
  AgentLeadsRoute: typeof AgentLeadsRoute
  AgentMessagesRoute: typeof AgentMessagesRoute
  AgentPaymentsRoute: typeof AgentPaymentsRoute
  AgentProfileRoute: typeof AgentProfileRoute
  AgentVerificationRoute: typeof AgentVerificationRoute
  InspectorAvailabilityRoute: typeof InspectorAvailabilityRoute
  InspectorDashboardRoute: typeof InspectorDashboardRoute
  InspectorEarningsRoute: typeof InspectorEarningsRoute
  InspectorProfileRoute: typeof InspectorProfileRoute
  InspectorReportsRoute: typeof InspectorReportsRoute
  LandlordAgentsRoute: typeof LandlordAgentsRoute
  LandlordInspectionsRoute: typeof LandlordInspectionsRoute
  LandlordMessagesRoute: typeof LandlordMessagesRoute
  LandlordPaymentsRoute: typeof LandlordPaymentsRoute
  LandlordProfileRoute: typeof LandlordProfileRoute
  LandlordVerificationRoute: typeof LandlordVerificationRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  RoommatesIdRoute: typeof RoommatesIdRoute
  RoommatesNewRoute: typeof RoommatesNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgentIndexRoute: typeof AgentIndexRoute
  LandlordIndexRoute: typeof LandlordIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  RoommatesIndexRoute: typeof RoommatesIndexRoute
  AdminAgreementsIdRoute: typeof AdminAgreementsIdRoute
  AgentAgreementsIdRoute: typeof AgentAgreementsIdRoute
  AgentPropertiesNewRoute: typeof AgentPropertiesNewRoute
  InspectorInspectionsIdRoute: typeof InspectorInspectionsIdRoute
  LandlordAgreementsIdRoute: typeof LandlordAgreementsIdRoute
  LandlordPropertiesNewRoute: typeof LandlordPropertiesNewRoute
  AdminAgreementsIndexRoute: typeof AdminAgreementsIndexRoute
  AgentAgreementsIndexRoute: typeof AgentAgreementsIndexRoute
  AgentPropertiesIndexRoute: typeof AgentPropertiesIndexRoute
  InspectorInspectionsIndexRoute: typeof InspectorInspectionsIndexRoute
  LandlordAgreementsIndexRoute: typeof LandlordAgreementsIndexRoute
  LandlordPropertiesIndexRoute: typeof LandlordPropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections': {
      id: '/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof InspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inspections': {
      id: '/admin/inspections'
      path: '/admin/inspections'
      fullPath: '/admin/inspections'
      preLoaderRoute: typeof AdminInspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/admin/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suspensions': {
      id: '/admin/suspensions'
      path: '/admin/suspensions'
      fullPath: '/admin/suspensions'
      preLoaderRoute: typeof AdminSuspensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/availability': {
      id: '/agent/availability'
      path: '/agent/availability'
      fullPath: '/agent/availability'
      preLoaderRoute: typeof AgentAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/inspections': {
      id: '/agent/inspections'
      path: '/agent/inspections'
      fullPath: '/agent/inspections'
      preLoaderRoute: typeof AgentInspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/leads': {
      id: '/agent/leads'
      path: '/agent/leads'
      fullPath: '/agent/leads'
      preLoaderRoute: typeof AgentLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/messages': {
      id: '/agent/messages'
      path: '/agent/messages'
      fullPath: '/agent/messages'
      preLoaderRoute: typeof AgentMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/payments': {
      id: '/agent/payments'
      path: '/agent/payments'
      fullPath: '/agent/payments'
      preLoaderRoute: typeof AgentPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/profile': {
      id: '/agent/profile'
      path: '/agent/profile'
      fullPath: '/agent/profile'
      preLoaderRoute: typeof AgentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/verification': {
      id: '/agent/verification'
      path: '/agent/verification'
      fullPath: '/agent/verification'
      preLoaderRoute: typeof AgentVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector/availability': {
      id: '/inspector/availability'
      path: '/inspector/availability'
      fullPath: '/inspector/availability'
      preLoaderRoute: typeof InspectorAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector/dashboard': {
      id: '/inspector/dashboard'
      path: '/inspector/dashboard'
      fullPath: '/inspector/dashboard'
      preLoaderRoute: typeof InspectorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector/earnings': {
      id: '/inspector/earnings'
      path: '/inspector/earnings'
      fullPath: '/inspector/earnings'
      preLoaderRoute: typeof InspectorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector/profile': {
      id: '/inspector/profile'
      path: '/inspector/profile'
      fullPath: '/inspector/profile'
      preLoaderRoute: typeof InspectorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector/reports': {
      id: '/inspector/reports'
      path: '/inspector/reports'
      fullPath: '/inspector/reports'
      preLoaderRoute: typeof InspectorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/': {
      id: '/landlord/'
      path: '/landlord'
      fullPath: '/landlord/'
      preLoaderRoute: typeof LandlordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/agents': {
      id: '/landlord/agents'
      path: '/landlord/agents'
      fullPath: '/landlord/agents'
      preLoaderRoute: typeof LandlordAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/inspections': {
      id: '/landlord/inspections'
      path: '/landlord/inspections'
      fullPath: '/landlord/inspections'
      preLoaderRoute: typeof LandlordInspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/messages': {
      id: '/landlord/messages'
      path: '/landlord/messages'
      fullPath: '/landlord/messages'
      preLoaderRoute: typeof LandlordMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/payments': {
      id: '/landlord/payments'
      path: '/landlord/payments'
      fullPath: '/landlord/payments'
      preLoaderRoute: typeof LandlordPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/profile': {
      id: '/landlord/profile'
      path: '/landlord/profile'
      fullPath: '/landlord/profile'
      preLoaderRoute: typeof LandlordProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/verification': {
      id: '/landlord/verification'
      path: '/landlord/verification'
      fullPath: '/landlord/verification'
      preLoaderRoute: typeof LandlordVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roommates/': {
      id: '/roommates/'
      path: '/roommates'
      fullPath: '/roommates/'
      preLoaderRoute: typeof RoommatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roommates/$id': {
      id: '/roommates/$id'
      path: '/roommates/$id'
      fullPath: '/roommates/$id'
      preLoaderRoute: typeof RoommatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roommates/new': {
      id: '/roommates/new'
      path: '/roommates/new'
      fullPath: '/roommates/new'
      preLoaderRoute: typeof RoommatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agreements/': {
      id: '/admin/agreements/'
      path: '/admin/agreements'
      fullPath: '/admin/agreements/'
      preLoaderRoute: typeof AdminAgreementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agreements/$id': {
      id: '/admin/agreements/$id'
      path: '/admin/agreements/$id'
      fullPath: '/admin/agreements/$id'
      preLoaderRoute: typeof AdminAgreementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/agreements/': {
      id: '/agent/agreements/'
      path: '/agent/agreements'
      fullPath: '/agent/agreements/'
      preLoaderRoute: typeof AgentAgreementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/agreements/$id': {
      id: '/agent/agreements/$id'
      path: '/agent/agreements/$id'
      fullPath: '/agent/agreements/$id'
      preLoaderRoute: typeof AgentAgreementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/properties/': {
      id: '/agent/properties/'
      path: '/agent/properties'
      fullPath: '/agent/properties/'
      preLoaderRoute: typeof AgentPropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/properties/new': {
      id: '/agent/properties/new'
      path: '/agent/properties/new'
      fullPath: '/agent/properties/new'
      preLoaderRoute: typeof AgentPropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector/inspections/': {
      id: '/inspector/inspections/'
      path: '/inspector/inspections'
      fullPath: '/inspector/inspections/'
      preLoaderRoute: typeof InspectorInspectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector/inspections/$id': {
      id: '/inspector/inspections/$id'
      path: '/inspector/inspections/$id'
      fullPath: '/inspector/inspections/$id'
      preLoaderRoute: typeof InspectorInspectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/agreements/': {
      id: '/landlord/agreements/'
      path: '/landlord/agreements'
      fullPath: '/landlord/agreements/'
      preLoaderRoute: typeof LandlordAgreementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/agreements/$id': {
      id: '/landlord/agreements/$id'
      path: '/landlord/agreements/$id'
      fullPath: '/landlord/agreements/$id'
      preLoaderRoute: typeof LandlordAgreementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/properties/': {
      id: '/landlord/properties/'
      path: '/landlord/properties'
      fullPath: '/landlord/properties/'
      preLoaderRoute: typeof LandlordPropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/properties/new': {
      id: '/landlord/properties/new'
      path: '/landlord/properties/new'
      fullPath: '/landlord/properties/new'
      preLoaderRoute: typeof LandlordPropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  InspectionsRoute: InspectionsRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SavedRoute: SavedRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminInspectionsRoute: AdminInspectionsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSuspensionsRoute: AdminSuspensionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AgentAvailabilityRoute: AgentAvailabilityRoute,
  AgentInspectionsRoute: AgentInspectionsRoute,
  AgentLeadsRoute: AgentLeadsRoute,
  AgentMessagesRoute: AgentMessagesRoute,
  AgentPaymentsRoute: AgentPaymentsRoute,
  AgentProfileRoute: AgentProfileRoute,
  AgentVerificationRoute: AgentVerificationRoute,
  InspectorAvailabilityRoute: InspectorAvailabilityRoute,
  InspectorDashboardRoute: InspectorDashboardRoute,
  InspectorEarningsRoute: InspectorEarningsRoute,
  InspectorProfileRoute: InspectorProfileRoute,
  InspectorReportsRoute: InspectorReportsRoute,
  LandlordAgentsRoute: LandlordAgentsRoute,
  LandlordInspectionsRoute: LandlordInspectionsRoute,
  LandlordMessagesRoute: LandlordMessagesRoute,
  LandlordPaymentsRoute: LandlordPaymentsRoute,
  LandlordProfileRoute: LandlordProfileRoute,
  LandlordVerificationRoute: LandlordVerificationRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  RoommatesIdRoute: RoommatesIdRoute,
  RoommatesNewRoute: RoommatesNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgentIndexRoute: AgentIndexRoute,
  LandlordIndexRoute: LandlordIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  RoommatesIndexRoute: RoommatesIndexRoute,
  AdminAgreementsIdRoute: AdminAgreementsIdRoute,
  AgentAgreementsIdRoute: AgentAgreementsIdRoute,
  AgentPropertiesNewRoute: AgentPropertiesNewRoute,
  InspectorInspectionsIdRoute: InspectorInspectionsIdRoute,
  LandlordAgreementsIdRoute: LandlordAgreementsIdRoute,
  LandlordPropertiesNewRoute: LandlordPropertiesNewRoute,
  AdminAgreementsIndexRoute: AdminAgreementsIndexRoute,
  AgentAgreementsIndexRoute: AgentAgreementsIndexRoute,
  AgentPropertiesIndexRoute: AgentPropertiesIndexRoute,
  InspectorInspectionsIndexRoute: InspectorInspectionsIndexRoute,
  LandlordAgreementsIndexRoute: LandlordAgreementsIndexRoute,
  LandlordPropertiesIndexRoute: LandlordPropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
